version: '3.8'

services:
  #app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  container_name: mini-jira-nestjs
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - .:/app
  #    - /app/node_modules
  #  environment:
  #    - NODE_ENV=development
  #  env_file:
  #    - config/env/.env.development
  #  command: npm run start:dev

  mongodb:
    image: mongo:6
    container_name: mini-jira-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
    driver: local